CC=g++
CFLAGS=-I/opt/intel/opencl/include -I. -std=c++11  -Wno-deprecated-declarations
LDFLAGS=-lOpenCL -L/opt/intel/opencl

EXEC=MotionEstimation

all:
	$(CC) -o $(EXEC) *.cpp $(CFLAGS) $(LDFLAGS) 	






